#!/bin/bash

PROGRAM=""
NAME=""
TITLE=""

while getopts ":p:n:t:" opt; do
  case $opt in
    p)
      PROGRAM=$OPTARG
      ;;
    n)
      NAME=$OPTARG
      ;;
    t)
      TITLE=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

if [ -z "$NAME" ]; then
    NAME=$PROGRAM
fi

if [ -z "$PROGRAM" ]; then
    PROGRAM=$NAME
fi

PID="$(pidof $NAME)"

if [ -z "$PID" ]; then
    $PROGRAM &>/dev/null &
fi

if [ -z "$TITLE" ]; then
    wmctrl -a $NAME
else
    wmctrl -a $TITLE
fi
