#!/bin/bash

PROGRAM=""
NAME=""
TITLE=""

while getopts ":p:n:t:a:" opt; do
  case $opt in
    p)
      PROGRAM=$OPTARG
      ;;
    n)
      NAME=$OPTARG
      ;;
    t)
      TITLE=$OPTARG
      ;;
    a)
      if [ -z "$NAME" ]; then
          NAME=$OPTARG
      fi

      if [ -z "$PROGRAM" ]; then
          PROGRAM=$OPTARG
      fi

      if [ -z "$TITLE" ]; then
          TITLE=$OPTARG
      fi
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

PID="$(pidof $NAME)"

if [ -z "$PID" ]; then
    $PROGRAM &>/dev/null &
fi

if [ -n "$TITLE" ]; then
  wmctrl -a $TITLE
fi
