#!/bin/bash

PROGRAM=""
NAME=""
TITLE=""
WM_CLASS_NAME=""

while getopts ":p:n:t:a:x:" opt; do
  case $opt in
    p)
      PROGRAM=$OPTARG
      ;;
    n)
      NAME=$OPTARG
      ;;
    t)
      TITLE=$OPTARG
      ;;
    x)
      WM_CLASS_NAME=$OPTARG
      ;;
    a)
      if [ -z "$NAME" ]; then
          NAME=$OPTARG
      fi

      if [ -z "$PROGRAM" ]; then
          PROGRAM=$OPTARG
      fi

      if [ -z "$TITLE" ] && [ -z "$WM_CLASS_NAME" ]; then
          TITLE=$OPTARG
      fi
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

PID="$(pidof $NAME)"
echo $NAME

if [ -z "$PID" ]; then
    $PROGRAM &>/dev/null &
fi

if [ -n "$TITLE" ]; then
  wmctrl -a $TITLE
elif [ -n "$WM_CLASS_NAME" ]; then
  wmctrl -xa $WM_CLASS_NAME
fi
